### ISSUE TITLE
Timestamp age limit not working 

### ISSUE THREAD

**Issue by TRehfeldt** [wells/guacamole-auth-hmac-config#1]
Hi,

i sucessfully installed the guacamole HMAC Authentication Provider in Guacamole 0.9.9. Its works verry well! But if i copy the URL including the signature some minutes later to a nother Browser or Computer i can successfully establish a new SSH session. The timout is set to 1000 in guacamole.properties and in the URL.

What I do wrong?
Thanks in advance, Tilmann

**Comment by wells** [comment]
Perhaps your HMAC signature has set a timestamp for UTC or something that makes it valid for longer than one second. The timestamp encrypted in the HMAC signature needs to be in the same timezone as the timezone that the guacamole server has. 

The tests supplied with this plugin check for invalidation of timestamps as well.

**Comment by TRehfeldt** [comment]
Hi, 

many thanks for your Response! I have reinstalled the Plug-In and made the configuration again. And it's working! So it looks like I have done something wrong. But now i have new Problem. Some Connections are successfule and other do not. 

Working URL:
_https://myserver.mydomain.com/guacamole/#/client/FDHDEMOKALI01?timestamp=1468305206000&connection=FDHDEMOKALI01&signature=bpJY1Wc2vouvnnxM557EPIqguo4%3D_

Not Working URL:
_https://myserver.mydomain.com/guacamole/#/client/FDHDEMOW2K12?timestamp=1468305085000&connection=FDHDEMOW2K12&signature=ErY4EyJyEYRar%2FxnN2ISAT0TTKs%3D_

Debug-File Output:
_Jul 12 08:40:13 fdhberdg01 server: 08:40:13.442 [http-bio-8443-exec-18] DEBUG c.b.g.n.h.HmacAuthenticationProvider - kv: connection = FDHDEMOW2K12
Jul 12 08:40:13 fdhberdg01 server: 08:40:13.442 [http-bio-8443-exec-18] DEBUG c.b.g.n.h.HmacAuthenticationProvider - kv: signature = ErY4EyJyEYRar/xnN2ISAT0TTKs=
Jul 12 08:40:13 fdhberdg01 server: 08:40:13.442 [http-bio-8443-exec-18] DEBUG c.b.g.n.h.HmacAuthenticationProvider - kv: token = e2470c986233f8ef9183b1e1d440c8445d0bd99b92ec11ccde7808a1e6d2355e
Jul 12 08:40:13 fdhberdg01 server: 08:40:13.442 [http-bio-8443-exec-18] DEBUG c.b.g.n.h.HmacAuthenticationProvider - kv: timestamp = 1468305609000
Jul 12 08:40:13 fdhberdg01 server: 08:40:13.442 [http-bio-8443-exec-18] DEBUG c.b.g.n.h.HmacAuthenticationProvider - Reading configuration file: "/usr/share/tomcat/.guacamole/hmac-config.xml"
Jul 12 08:40:13 fdhberdg01 server: 08:40:13.443 [http-bio-8443-exec-18] DEBUG c.b.g.n.h.HmacAuthenticationProvider - Get hmac signature: ErY4EyJyEYRar/xnN2ISAT0TTKs=
Jul 12 08:40:13 fdhberdg01 server: 08:40:13.443 [http-bio-8443-exec-18] DEBUG c.b.g.n.h.HmacAuthenticationProvider - Get connection: FDHDEMOW2K12
Jul 12 08:40:13 fdhberdg01 server: 08:40:13.443 [http-bio-8443-exec-18] DEBUG c.b.g.n.h.HmacAuthenticationProvider - Timestamp Age Limit: 10000
Jul 12 08:40:13 fdhberdg01 server: 08:40:13.443 [http-bio-8443-exec-18] DEBUG c.b.g.n.h.HmacAuthenticationProvider - Check timestamp: true
Jul 12 08:40:13 fdhberdg01 server: 08:40:13.443 [http-bio-8443-exec-18] DEBUG c.b.g.n.h.HmacAuthenticationProvider - Get hmac message: 1468305609000rdp10000001hostname172.27.184.3port3389
Jul 12 08:40:13 fdhberdg01 server: 08:40:13.443 [http-bio-8443-exec-18] DEBUG o.g.g.n.b.r.a.AuthenticationService - Anonymous authentication attempt from 172.31.10.11 failed._

Configuration File:
`<configs>`
`<config name="FDHDEMOKALI01" protocol="ssh">`
`<param name="hostname" value="172.27.184.2" />`
`<param name="port" value="22" />`
`</config>`
`<config name="FDHDEMOW2K12" protocol="rdp">`
`<param name="hostname" value="172.27.184.3" />`
`<param name="port" value="3389" />`
`</config>`
`</configs>`

Could you saye what is going wrong?

**Comment by wells** [comment]
If your link timeout is 1 second (1000 ms), your guacamole signature could be expiring before the server responds. Try extending the timeout of the link so it remains valid long enough for the guacamole server to handle the response (i.e. 10000 ms).

**Comment by TRehfeldt** [comment]
I already extend the timeout to 10.000 or more ms. but it doesn't help. I do not believe that it has something todo with the timestamp because the log says "Check timestamp: true".

In the Logfile i see the following entry: "EBUG o.g.g.n.b.r.a.AuthenticationService - Anonymous authentication attempt from 172.31.10.11 failed." 
Could this be the issue? why is there a other authentication provider ("o.g.g.n.b.r.a.AuthenticationService")?

**Comment by wells** [comment]
Guacamole 0.9.9 is capable of running multiple authentication providers. If one fails, the other providers should be allowed to attempt to authenticate the user as well before giving completely up. I'm not sure what this other provider is in your case.

**Comment by wells** [comment]
@TRehfeldt you may need to add a `<param name="ignore-cert" value="true" />` into the RDP configuration.

I also have a sample config for RDP that I know works:
https://github.com/wells/guacamole-auth-hmac-config/blob/master/src/test/resources/hmac-config.xml
