### ISSUE TITLE
Just redirected back to login page

### ISSUE THREAD

**Issue by raynor2k** [wells/guacamole-auth-hmac-config#2]
Hi together. I have installed this plugin and configured guacamole exactly as described here, but I just redirected back to the login page with the generated URL. Do you have an idea whats going wrong?

**Comment by wells** [comment]
You need to have a valid HMAC key generated for the link when attempting to visit the guacamole instance. My guess is that you have different timestamps / timezones between the server generating the URL and the server hosting guacamole.

**Comment by raynor2k** [comment]
Hi - thank you for your prompt reply. I am using your "generate_url_example.php" script, modified for my rdp connection, to generate the URL. This script and the guacamole server is running on the same server. The "guacamole.properties" and "hmac-config.xml" is exactly configured as described in your instruction but for my rdp connection. It seems there is an permission problem in my configuration. In the console of my Chrome browser I get the message "...guacamole/api/tokens 403 (Forbidden)". I hope you can help me again with these information.
